
apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-submariner
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
      - name: deploy-submariner
        image: quay.io/langley_millard_ibm/deploy-submariner
        imagePullPolicy: Always
        env:
        - name: CLUSTER_LIST
          value: aws-cluster-0, aws-cluster-2
      restartPolicy: Never
  backoffLimit: 2
